worker_processes auto;

events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cdn:10m max_size=1g inactive=60d use_temp_path=off;

    server {
        listen 80;

        location / {
            limit_except GET HEAD {
                deny all;
            }

            proxy_pass http://minio:9000/songs/;
            proxy_cache cdn;
            proxy_cache_valid 200 30d;
            proxy_cache_valid 404 1m;
            proxy_cache_lock on;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

            add_header X-Cache-Status $upstream_cache_status always;
        }
    }
}
